### ISSUE TITLE
Blue ball drops

### ISSUE THREAD

**Issue by phghub** [phghub/brickout#4]
파란색 공 아이템을 먹으면 게임 내 존재하는 공이 해당 자리에서 * 3 되는 기능

**Comment by Ksuwon** [comment]
파란색 공 아이템 구현 올렸습니다

**Comment by phghub** [comment]
지금은 먹은 파란색 공이 사라지면 크기 증가가 풀리는데, 공이 사라져도 아이템 효과는 풀리지 않도록 하면 좋을 것 같습니다

**Comment by Ksuwon** [comment]
수정했습니다!

**Comment by phghub** [comment]
확인했습니다 수고하셨습니다
